version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5556:5556"
    volumes:
      - ../app:/app/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
